### PR TITLE
Board initial graphical implementation

### PR DESCRIPTION
**Pull request by potatoeggy**
The following large changes have been made:

 - There's a board now
 - Everything is white to make it look a little bit nicer
 - Linking between all menus and the game is complete
 - MainWindow is now both the global event handler and the game settings manager
    - This was done so that all classes can access their required settings when they need to and so a move timer could be run without researching how to multithread 
    - As a result, GameWindow is like a frontend to the MainWindow backend to the Board backend
 - Every class now has mutator methods because of settings management

Oh boy timers is going to be a pain

### CODE REVIEW

**Comment by potatoeggy** [comment]
@bob2957 please review if you can; this is a big merge

**Comment by vincentjguo** [comment]
The window is cutting off on my screen, it's too tall

**Comment by vincentjguo** [comment]
Maybe make it full screen?

**Comment by potatoeggy** [comment]
Interesting. It's well within the window for me. Can you attach a screenshot?
image

**Comment by vincentjguo** [comment]
[yep](https://gyazo.com/55a713966dcf30eaf2bdf1ef62954792)

**Comment by potatoeggy** [comment]
Interesting. And your display is 1920×1080? The window reaches the top of the screen?

**Comment by vincentjguo** [comment]
yep it's 1920x1080

**Comment by potatoeggy** [comment]
Swing does not support scaling until JDK 9. Unfortunately, this means that those with a 1920x1080 resolution and with display scaling greater than 1.25 will not be able to see the full window.
Nothing we can do, though.

**Pull request merged**
