### PR TITLE
Rearrange functions to make slaves obey their master, initial player v player support

### LINKED ISSUE #23: frontend: clean up import statements
Right now it's a mix of VSCode auto-generated imports and `import java.awt.*`.

### PR DESCRIPTION
**Pull request by potatoeggy**
This PR implements the following:
 - Implemented switching players
 - Shows current player turn using name from New Game menu
 - Disables placing more pieces after the game ends
 - Handles draws
 - Disables saving when quitting after the game ends
 - Refactored accessor and mutator methods so that MainWindow sets and gets instead of the instantiated classes getting from Main

**The game is now playable between two players.**

I have no clue how to implement move timers without threading, since the timers have to reset when a button is pressed, and Swing is not thread-safe. That idea might have to die.

### CODE REVIEW

**Comment by potatoeggy** [comment]
A move timer is going to implemented in this PR too.

**Review by vincentjguo — APPROVED** [review]
Looks good

**Comment by vincentjguo** [comment]
The move timer still hasn't been implemented yet right?

**Comment by potatoeggy** [comment]
Timer has been completed

**Comment by potatoeggy** [comment]
This PR is getting a little big so I think I'll make game over/random piece/whatever happens when the timer ends in another PR.

**Comment by vincentjguo** [comment]
Timer doesn't work

**Comment by potatoeggy** [comment]
Can you describe the issue? You need to enable the timer as it is off by default.

**Comment by vincentjguo** [comment]
It shows set time + 1 and it doesn't update

**Comment by potatoeggy** [comment]
Are you using MainWindow to call GameWindow?

**Comment by vincentjguo** [comment]
Im assuming thats what your program is doing right?

**Comment by potatoeggy** [comment]
It should be. I assume IntelliJ isn't doing anything weird when creating objects.

**Comment by vincentjguo** [comment]
No Intellij shouldn't change anything. Does it work on your side?

**Comment by vincentjguo** [comment]
Where do you set `moveTimerInternal`?

**Comment by potatoeggy** [comment]
It does work on my side (more or less) perfectly.

`moveTimerInternal` is used in `MainWindow` and is manipulated in `actionPerformed` and in `main`.

I pushed a few changes. Does that fix anything?

**Comment by vincentjguo** [comment]
nope time is still stuck and for some reason it's always 1 more than the value is set it at.

Does this have something to do with a multithreading issue?

**Comment by potatoeggy** [comment]
It might. Right now I'm using a hacky solution to work around having to actually implement threading.

The +1 is from 
`return moveTimerEnabler.isSelected() ? Integer.parseInt(((String) moveTimerSelect.getSelectedItem()).substring(0, 2).trim()) + 1 : -1;`
in `optionsMenu`, but the timer should be updated by the loops in `main`. I'm going to make a new branch with some debug code.

**Comment by bob2957** [comment]
The +1 is from... what?

**Comment by vincentjguo** [comment]
One more thing, save and quit should close the program

**Comment by potatoeggy** [comment]
Done

**Comment by vincentjguo** [comment]
[This sometimes happens](https://gyazo.com/1a00b933521109d9b1d0db002bf6ee0b)

The bottom has this weird overlapping rectangle

**Comment by potatoeggy** [comment]
...only sometimes?

**Comment by vincentjguo** [comment]
sometimes it's not there, sometimes it covers half the board

**Comment by potatoeggy** [comment]
but java doesn't work that way *swing* doesn't let you overlap things *what is happening*

what version of java is your compiler using?

**Comment by potatoeggy** [comment]
i'm grasping at straws here

**Comment by potatoeggy** [comment]
screw it

**Comment by vincentjguo** [comment]
Wait does it happen on your side?

**Comment by potatoeggy** [comment]
not at all

**Comment by vincentjguo** [comment]
That's fine then, it doesn't matter

**Pull request merged**
