### PR TITLE
Improved Win checking and re-enabled alpha beta pruning

### LINKED ISSUE #3: Alpha-Beta Pruning
I should probably add this, it makes the AI much faster

### PR DESCRIPTION
**Pull request by vincentjguo**
Changed win checking so it would check for a win each time the AI places a token instead of checking every single token.

Added variable AI.abPruning to toggle AB-pruning. Right now AB-pruning seems to be working, but the AI makes unconventional moves - perhaps a feature?

Resolves #3

### CODE REVIEW

**Comment by vincentjguo** [comment]
@potatoeggy can you try to break the AI? Just play around with it and notify me if the AI does something stupid

**Comment by potatoeggy** [comment]
Performance is decent against humans somewhat ish. It still becomes exponentially slower over time, and it takes 5-10 s per move after 20 or so chips still.

**Review by potatoeggy — APPROVED** [review]
Please remove the debug and commented code before merge. Aside from that, everything seems to work better than before.

**Comment by potatoeggy** [comment]
image
The AI spent the last three moves adding three yellows in the two rightmost columns

**Comment by potatoeggy** [comment]
image
Also, it took until now to go for the win.

**Comment by vincentjguo** [comment]
wait did you make the AI go second again? I haven't implemented this yet, so it would choose the worse possible outcomes.

**Comment by potatoeggy** [comment]
...really? Yeah, player 1 was me and player 2 was the computer

**Comment by vincentjguo** [comment]
Also the AI is kinda toxic - if it knows it's going to win no matter what, it will delay the win until the last possible moment, nothing I can do here to fix it, but it works.

**Comment by vincentjguo** [comment]
> ...really? Yeah, player 1 was me and player 2 was the computer

I think player 1 places down `1` on the backend board, and the AI thinks itself is `1` so that might mess things up in the future. One way to make the AI go second is to make the player place down `2` on the backend board when going first.

**Comment by potatoeggy** [comment]
That's a hacky workaround. Is there a way to pass the AI's number as a parameter?

**Comment by potatoeggy** [comment]
We can hardcode `0` as nothing, `self` as the AI's pieces, and `!= 0 && != self` as the player's.

**Comment by vincentjguo** [comment]
I could the parameter thing but that would take a lot of refactoring that I'd rather not do. 

The word `self` can't be recorded on the integer array so that won't work.
Of course, if I was smart, I would have made the AI `3` at the start, but now it's kinda too late.

**Comment by potatoeggy** [comment]
Sorry, I meant to pass `self` as an integer parameter. I'll take a look.

**Comment by potatoeggy** [comment]
Nope never mind I'm not taking a look

**Comment by vincentjguo** [comment]
Lol

Also I don't know what you mean about `self` as an int param

**Comment by potatoeggy** [comment]
The comment was combined with the one before it, with `self` being the AI's number as a parameter

```java
static ArrayList<Integer> minMax(Board b, int d, int p, int alpha, int beta, int self)
    if (depth == 0) {
        if (board[1][0] == self) {
            // it's an ai piece
        } else if (board[1][0] != 0) {
            // it's the other player's piece
        }
    }
}
```

**Comment by vincentjguo** [comment]
Yes but the board would track the player's piece as a `1` if they go first. The AI would think that the `1` is its piece.

**Comment by potatoeggy** [comment]
The first part is fine, that's intended, and that's why this system is more flexible, since (after changing all the hardcoded numbers) the number no longer corresponds to a particular player type (AI can be 1 or 2). The current player (1 or 2) can be passed to the method, and the AI would make a move for that current player.

**Comment by potatoeggy** [comment]
Really, any two numbers can be passed, as long as *exactly* two different numbers are ever passed, allowing for AI v AI stuff to work.

**Comment by vincentjguo** [comment]
I see what you mean, in that case, the self variable won't be needed, all you need to do is call minmax with the `player` parameter as 2 and with a loop that is able to find the smallest value out of the returned array list.

**Pull request merged**
