### PR TITLE
Options menu initial implementation

### PR DESCRIPTION
**Pull request by potatoeggy**
The first iteration of the (incredibly small) options menu, along with complete navigation and lots of under-the-hood tweaks.

### CODE REVIEW

**Comment by potatoeggy** [comment]
Please do give it a clickaround.

**Comment by potatoeggy** [comment]
Oh yes. Also, lots of documentation was added.

**Review by vincentjguo — CHANGES_REQUESTED** [review]
The window is still too small, the return to main menu button is cut off. Also, the options menu has a computer difficulty setting, which is redundant as the player menu has one too. I suggest keeping the player menu's difficulty setting but removing the options menu's one.

**Comment by potatoeggy** [comment]
> The window is still too small, the return to main menu button is cut off. 

Odd, that doesn't happen to me. `setSize` should have fixed that. Can you send a screenshot of what it looks like?

> Also, the options menu has a computer difficulty setting, which is redundant as the player menu has one too. I suggest keeping the player menu's difficulty setting but removing the options menu's one.

Ah yes, my bad. I intend to keep it in options since otherwise the menu is almost empty. I'd rather be able to change the difficulty on-the-fly, with the default being "Normal".

**Comment by bob2957** [comment]
[Here's what the menu looks for me](https://gyazo.com/db7444b63158712b9cf98d5237de946b)

**Comment by vincentjguo** [comment]
Everything looks good

**Review by vincentjguo — APPROVED** [review]

**Comment by vincentjguo** [comment]
wait hold up i think i approved the old version?

**Comment by vincentjguo** [comment]
Ok nevermind I just tested it, it's all good

**Pull request merged**
