### PR TITLE
Frontend work to allow interaction between ai and gooey

### PR DESCRIPTION
**Pull request by potatoeggy**
Depends on the ai_helper branch.

### CODE REVIEW

**Comment by vincentjguo** [comment]
Just putting this out there for more visibility

AI.fullCol needs to be reset every time a new game is created. Not sure where the New Game action is so please fix this @potatoeggy thanks.

**Comment by vincentjguo** [comment]
Also resolves #29

**Comment by potatoeggy** [comment]
The way a new game is made is that GameWindow is simply re-initialised from MainWindow.

**Comment by vincentjguo** [comment]
Ah but can you reset the ArrayList before you re-initialize MainWindow

**Comment by potatoeggy** [comment]
Which ArrayList?

**Comment by potatoeggy** [comment]
The code for creating a new game is here in `MainWindow`:
```
		else if (e.equals(newGameMenu.buttons[0])) {
			names = newGameMenu.getNames();
			players = newGameMenu.getPlayers();
			gameWindow = new GameWindow(this);

			// pass information from new game and options, if configured
			gameWindow.setNames(names);
			gameWindow.setPlayers(players);
			gameWindow.setTimer(moveTimerInternal);
			gameWindow.setDifficulty(cpuDifficulty);
			if (players[0] == 1) gameWindow.cpuInit();
			add(gameWindow);
			transition(newGameMenu, gameWindow);
```

**Comment by potatoeggy** [comment]
Everything should be reinitialised automatically.

**Comment by vincentjguo** [comment]
Ok cool i can write in the code to reset the array

**Comment by potatoeggy** [comment]
This branch is now ready to merge. Any complaints?

**Pull request merged**
